PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 70
  early_stop: 15
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 4
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 12
    spatial_embedding_dim: 24
    adaptive_embedding_dim: 12
    embed_dim: 0
    feed_forward_dim: 256
    num_heads0: 4
    num_heads1: 4
    num_heads2: 4
    num_layers: 6
    dropout: 0.1
    dropout1: 0.35
    dim: 2



